// zod compatibility subset used by the embedded DSH graph.
class ZodStr { parse(v) { if (typeof v !== 'string') throw new Error('zod: expected string'); return v } optional() { return this } nullable() { return this } refine() { return this } catch() { return this } min() { return this } max() { return this } regex() { return this } trim() { return this } email() { return this } url() { return this } uuid() { return this } startsWith() { return this } endsWith() { return this } transform(fn) { const s = this; return { parse(v) { return fn(s.parse(v)); } }; } default(d) { const s = this; return { parse(v) { return v ?? d } } } }
class ZodNull { parse(v) { if (v !== null) throw new Error('zod: expected null'); return null } nullable() { return this } }
class ZodUnion { constructor(ss) { this.ss = ss } parse(v) { for (const s of this.ss) { try { return s.parse(v) } catch {} } throw new Error('zod: union failed') } strict() { return this } nullable() { return this } optional() { return this } catch() { return this } refine() { return this } passthrough() { return this } transform(fn) { const s = this; return { parse(v) { return fn(s.parse(v)); } }; } }
class ZodObj { constructor(shape) { this.shape = shape } parse(v) { const o = {}; for (const k of Object.keys(this.shape)) o[k] = this.shape[k].parse(v?.[k]); return { ...o, ...v }; } strict() { return this } optional() { return this } nullable() { return this } transform(fn) { const s = this; return { parse(v) { return fn(s.parse(v)); } }; } refine() { return this } catch(fn) { const s = this; return { parse(v) { try { return s.parse(v); } catch (e) { return fn(e); } } }; } passthrough() { return this } }
class ZodLit { constructor(v) { this.v = v } parse(v) { if (v !== this.v) throw new Error('zod: literal mismatch'); return v } optional() { return this } nullable() { return this } }
class ZodDiscriminated { constructor(tag, variants) { this.tag = tag; this.variants = Array.isArray(variants) ? variants : Object.values(variants) } parse(v) { for (const r of this.variants) { try { return r.parse(v); } catch {} } throw new Error('zod: bad discriminator'); } optional() { return this } nullable() { return this } }
const chain = (fn) => Object.assign(fn, { int: () => fn, nonnegative: () => fn, positive: () => fn, min: () => fn, max: () => fn, optional: () => fn, nullable: () => fn, default: (d) => ({ parse(v) { return v ?? d; } }), parse: (v) => fn.parse(v) });
class ZodNum { parse(v) { if (typeof v !== 'number') throw new Error('zod: expected number'); return v } int() { return this } nonnegative() { return this } positive() { return this } min() { return this } max() { return this } optional() { return this } nullable() { return this } default(d) { const s = this; return { parse(v) { return v ?? d; } } } }
class ZodBool { parse(v) { if (typeof v !== 'boolean') throw new Error('zod: expected boolean'); return v } optional() { return this } nullable() { return this } }
class ZodArr { constructor(inner) { this.inner = inner } parse(v) { if (!Array.isArray(v)) throw new Error('zod: expected array'); return v.map((x) => this.inner ? this.inner.parse(x) : x); } optional() { return this } nullable() { return this } }
export const z = { string: () => new ZodStr(), null: () => new ZodNull(), number: () => new ZodNum(), boolean: () => new ZodBool(), array: (inner) => new ZodArr(inner), union: (...ss) => new ZodUnion(ss), object: (shape) => new ZodObj(shape), literal: (v) => new ZodLit(v), discriminatedUnion: (tag, variants) => new ZodDiscriminated(tag, variants) };
export default z;